version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:
  unit-test:
    working_directory: ~/pismo-challenge
    docker:
      - image: circleci/openjdk:11-jdk-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: Unit tests
          command: ./gradlew unitTest
  integration-test:
    working_directory: ~/pismo-challenge
    docker:
      - image: circleci/openjdk:11-jdk-stretch-node-browsers
    environment:
      JDBC_URL: jdbc:postgresql://localhost:5432/pismo-challenge
      JDBC_USER: postgres
      JDBC_PASSWORD: root
    steps:
      - run:
          name: Download Java 11
          command: |
            sudo apt update
            sudo apt install openjdk-11-jdk
      - checkout
      - run:
          name: Integration tests
          command: ./gradlew integrationTest
  api-test:
    working_directory: ~/pismo-challenge/postman
    docker:
      - image: circleci/node:stretch
      steps:
        - checkout
        - run:
            name: Install newman
            command: npm install -g newman
        - run:
            name: Run test collection
            command: newman run pismo-challenge-collection.json

  build:
    working_directory: ~/pismo-challenge
    docker:
      - image: circleci/openjdk:11-jdk-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: run build
          command: ./gradlew clean build

workflows:
  'Test, Build and Deploy Workflow':
    jobs:
      - unit-test
      - integration-test
      - api-test

      - build:
          requires:
            - unit-test
            - integration-test
            - api-test





