version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:
  start-application:
    machine: true
    steps:
      - checkout
      - run:
          command: docker-compose up --build

  unit-test:
    working_directory: ~/pismo-challenge
    docker:
      - image: circleci/openjdk:11-jdk-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: Unit tests
          command: ./gradlew unitTest

  integration-test:
    working_directory: ~/pismo-challenge
    machine: true
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      JAVA_TOOL_OPTIONS: "-Xmx4G"
      GRADLE_OPTS: "-Xmx4G -Dorg.gradle.daemon=false -DdisablePreDex"
    steps:
      - run:
          name: Download Java 11
          command: |
            sudo apt update
            sudo apt install openjdk-11-jdk
      - checkout
      - run:
          name: Integration tests
          command: ./gradlew integrationTest
  api-test:
    working_directory: ~/pismo-challenge
    docker:
      - image: circleci/node:stretch
    steps:
      - checkout
      - run:
          name: Run application
          command: docker-compose up --build -d
      - run:
          name: Install newman
          command: sudo npm install -g newman
      - run:
          name: Run test collection
          command: newman run postman/pismo-challenge-collection.json

  build:
    working_directory: ~/pismo-challenge
    docker:
      - image: circleci/openjdk:11-jdk-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: Building Jar application
          command: ./gradlew clean assemble

workflows:
  'Test, Build and Deploy Workflow':
    jobs:
      - unit-test
      - integration-test

      - build:
          requires:
            - unit-test
            - integration-test
      - start-application:
          requires:
            - build
      - api-test:
          requires:
            - build
            - start-application





